dbt_demo_pro:
  outputs:
    dev:
      account: isb70292
      database: DBT_DB
      password: SKrljtx02
      role: ACCOUNTADMIN
      schema: TEST_SCHEMA
      threads: 4
      type: snowflake
      user: gebicket
      warehouse: COMPUTE_WH
    prod:
      account: isb70292.snowflakecomputing.com
      database: dbt_db_prd
      password: SKrljtx02
      role: ACCOUNTADMIN
      schema: test_schema
      threads: 4
      type: snowflake
      user: gebicket
      warehouse: COMPUTE_WH
  target: dev
